'use client';

import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Theme = 'light' | 'dark' | 'system';
type Language = 'en' | 'uz' | 'ru';

interface SettingsContextType {
    theme: Theme;
    setTheme: (theme: Theme) => void;
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
}

const SettingsContext = createContext<SettingsContextType | undefined>(undefined);

// Translations
const translations: Record<Language, Record<string, string>> = {
    en: {
        // Navigation
        'nav.dashboard': 'Dashboard',
        'nav.patients': 'Patients',
        'nav.appointments': 'Appointments',
        'nav.visits': 'Visits',
        'nav.services': 'Services',
        'nav.staff': 'Staff',
        'nav.contracts': 'Contracts',
        'nav.expenses': 'Expenses',
        'nav.salaries': 'Salaries',
        'nav.reports': 'Reports',
        'nav.activity': 'Activity',
        'nav.settings': 'Settings',
        'nav.logout': 'Logout',
        'nav.brand': 'Medical CRM',
        // Common
        'common.save': 'Save',
        'common.cancel': 'Cancel',
        'common.delete': 'Delete',
        'common.edit': 'Edit',
        'common.create': 'Create',
        'common.add': 'Add',
        'common.search': 'Search',
        'common.loading': 'Loading...',
        'common.noData': 'No data available',
        'common.refresh': 'Refresh',
        'common.filter': 'Filter',
        'common.to': 'to',
        'common.actions': 'Actions',
        'common.name': 'Name',
        'common.email': 'Email',
        'common.phone': 'Phone',
        'common.status': 'Status',
        'common.active': 'Active',
        'common.inactive': 'Inactive',
        'common.date': 'Date',
        'common.time': 'Time',
        'common.price': 'Price',
        'common.duration': 'Duration',
        'common.notes': 'Notes',
        'common.amount': 'Amount',
        'common.select': 'Select...',
        'common.confirm': 'Are you sure?',
        'common.done': 'Done',
        // Settings
        'settings.title': 'Settings',
        'settings.appearance': 'Appearance',
        'settings.theme': 'Theme',
        'settings.themeLight': 'Light',
        'settings.themeDark': 'Dark',
        'settings.themeSystem': 'System',
        'settings.language': 'Language',
        // Login
        'login.title': 'Medical CRM',
        'login.subtitle': 'Sign in to your account',
        'login.email': 'Email',
        'login.password': 'Password',
        'login.emailPlaceholder': 'Enter your email',
        'login.passwordPlaceholder': 'Enter your password',
        'login.submit': 'Sign In',
        'login.submitting': 'Signing in...',
        // Dashboard titles
        'dashboard.title': 'Dashboard',
        'dashboard.reception': 'Reception Dashboard',
        'dashboard.doctor': 'Doctor Dashboard',
        'dashboard.boss': 'Boss Dashboard',
        'dashboard.patientsToday': 'New Patients Today',
        'dashboard.visitsToday': 'Visits Today',
        'dashboard.revenueToday': 'Revenue Today',
        // Patients
        'patients.title': 'Patients',
        'patients.add': 'Add Patient',
        'patients.search': 'Search patients...',
        'patients.firstName': 'First Name',
        'patients.lastName': 'Last Name',
        'patients.gender': 'Gender',
        'patients.male': 'Male',
        'patients.female': 'Female',
        'patients.other': 'Other',
        'patients.noPatients': 'No patients found',
        // Appointments
        'appointments.title': 'Appointments',
        'appointments.today': "Today's Appointments",
        'appointments.book': 'Book Appointment',
        'appointments.patient': 'Patient',
        'appointments.doctor': 'Doctor',
        'appointments.dateTime': 'Date & Time',
        'appointments.selectPatient': 'Select Patient...',
        'appointments.selectDoctor': 'Select Doctor...',
        'appointments.noAppointments': 'No appointments today',
        // Visits
        'visits.title': 'Visits',
        'visits.today': "Today's Visits",
        'visits.todaySchedule': "Today's Schedule",
        'visits.start': 'Start Visit',
        'visits.complete': 'Complete Visit',
        'visits.completeTitle': 'Complete Visit',
        'visits.diagnosis': 'Diagnosis',
        'visits.diagnosisPlaceholder': 'Enter diagnosis...',
        'visits.diagnosisRequired': 'Diagnosis is required',
        'visits.notesPlaceholder': 'Additional notes...',
        'visits.serviceRequired': 'At least one service is required',
        'visits.noVisits': 'No visits today',
        'visits.noAppointments': 'No appointments today',
        'visits.total': 'Total',
        'visits.toothFormula': 'Tooth Formula',
        'visits.affectedTeeth': 'Affected Teeth',
        'visits.selectAffectedTeeth': 'Mark affected teeth',
        // Services
        'services.title': 'Medical Services',
        'services.add': 'Add Service',
        'services.name': 'Name',
        'services.description': 'Description',
        'services.qty': 'Qty',
        // Payment
        'payment.type': 'Payment Type',
        'payment.cash': 'Cash',
        'payment.card': 'Card',
        'payment.discount': 'Discount',
        'payment.discountType': 'Discount Type',
        'payment.discountValue': 'Discount Value',
        'payment.noDiscount': 'No Discount',
        'payment.percentage': 'Percentage',
        'payment.fixed': 'Fixed Amount',
        // Staff
        'staff.title': 'Staff Members',
        'staff.add': 'Add Staff',
        'staff.role': 'Role',
        'staff.doctor': 'Doctor',
        'staff.receptionist': 'Receptionist',
        // Contracts
        'contracts.title': 'Doctor Contracts',
        'contracts.add': 'Add Contract',
        'contracts.selectDoctor': 'Select a doctor',
        'contracts.sharePercent': 'Share Percentage (%)',
        'contracts.startDate': 'Start Date',
        'contracts.endDate': 'End Date (optional)',
        'contracts.ongoing': 'Ongoing',
        'contracts.noContracts': 'No contracts yet.',
        // Expenses
        'expenses.title': 'Expenses',
        'expenses.add': 'Add Expense',
        'expenses.category': 'Category',
        'expenses.rent': 'Rent',
        'expenses.utilities': 'Utilities',
        'expenses.supplies': 'Supplies',
        'expenses.marketing': 'Marketing',
        'expenses.salary': 'Salary',
        'expenses.other': 'Other',
        'expenses.note': 'Note (optional)',
        'expenses.noExpenses': 'No expenses recorded yet.',
        // Salaries
        'salaries.title': 'Staff Salaries',
        'salaries.add': 'Add Salary',
        'salaries.selectStaff': 'Select staff member',
        'salaries.monthlyAmount': 'Monthly Amount ($)',
        'salaries.effectiveFrom': 'Effective From',
        'salaries.noSalaries': 'No salaries configured yet.',
        // Activity
        'activity.title': 'Doctor Activity Log',
        'activity.allDoctors': 'All Doctors',
        'activity.noLogs': 'No activity logs yet.',
        'activity.entity': 'Entity',
        'activity.details': 'Details',
        'activity.action': 'Action',
        'activity.visitStarted': '🏥 Visit Started',
        'activity.visitFinished': '✅ Visit Completed',
        'activity.statusChanged': '📅 Status Changed',
        // Reports
        'reports.financialReports': 'Financial Reports',
        'reports.subtitle': 'Monthly financial overview and profit analysis',
        'reports.totalRevenue': 'Total Revenue',
        'reports.doctorEarnings': 'Doctor Earnings',
        'reports.expenses': 'Total Expenses',
        'reports.salaries': 'Staff Salaries',
        'reports.grossProfit': 'Gross Profit',
        'reports.netProfit': 'Net Profit',
        'reports.revenueByDoctor': 'Revenue by Doctor',
        'reports.expensesByCategory': 'Expenses by Category',
        'reports.profitBreakdown': 'Financial Breakdown',
        'reports.additionalStats': 'Additional Statistics',
        'reports.visitsCount': 'Total Visits',
        'reports.patientsCount': 'Patients',
        'reports.totalDiscount': 'Total Discounts',
        'reports.avgPerVisit': 'Avg. per Visit',
        'reports.noData': 'No data available for the selected period',
        // Table headers
        'table.earning': 'Earning',
        'table.revenue': 'Revenue',
        'table.service': 'Service',
        // Status
        'status.scheduled': 'Scheduled',
        'status.confirmed': 'Confirmed',
        'status.in_progress': 'In Progress',
        'status.completed': 'Completed',
        'status.cancelled': 'Cancelled',
        'status.no_show': 'No Show',
        'status.started': 'Started',
        // Treatment Plans
        'treatmentPlan.title': 'Treatment Plans',
        'treatmentPlan.create': 'Create Treatment Plan',
        'treatmentPlan.planTitle': 'Plan Title',
        'treatmentPlan.planTitlePlaceholder': 'e.g., Implant Installation',
        'treatmentPlan.steps': 'Steps',
        'treatmentPlan.addStep': 'Add Step',
        'treatmentPlan.stepDescription': 'Step Description',
        'treatmentPlan.stepPlaceholder': 'e.g., Cleaning, X-Ray',
        'treatmentPlan.noPlans': 'No treatment plans yet',
        'treatmentPlan.progress': 'Progress',
        'treatmentPlan.markComplete': 'Mark as Complete',
        'treatmentPlan.pending': 'Pending',
        'treatmentPlan.completed': 'Completed',
        'treatmentPlan.inProgress': 'In Progress',
        'treatmentPlan.patientPlans': 'Patient Treatment Plans',
        'treatmentPlan.save': 'Save',
        'treatmentPlan.finish': 'Finish & Pay',
        'treatmentPlan.saved': 'Treatment plan saved. Continue next visit.',
    },
    uz: {
        // Navigation
        'nav.dashboard': 'Boshqaruv paneli',
        'nav.patients': 'Bemorlar',
        'nav.appointments': 'Uchrashuvlar',
        'nav.visits': 'Tashriflar',
        'nav.services': 'Xizmatlar',
        'nav.staff': 'Xodimlar',
        'nav.contracts': 'Shartnomalar',
        'nav.expenses': 'Xarajatlar',
        'nav.salaries': 'Maoshlar',
        'nav.reports': 'Hisobotlar',
        'nav.activity': 'Faoliyat',
        'nav.settings': 'Sozlamalar',
        'nav.logout': 'Chiqish',
        'nav.brand': 'Medical CRM',
        // Common
        'common.save': 'Saqlash',
        'common.cancel': 'Bekor qilish',
        'common.delete': "O'chirish",
        'common.edit': 'Tahrirlash',
        'common.create': 'Yaratish',
        'common.add': "Qo'shish",
        'common.search': 'Qidirish',
        'common.loading': 'Yuklanmoqda...',
        'common.noData': "Ma'lumot yo'q",
        'common.refresh': 'Yangilash',
        'common.filter': 'Filtr',
        'common.to': 'gacha',
        'common.actions': 'Amallar',
        'common.name': 'Ism',
        'common.email': 'Elektron pochta',
        'common.phone': 'Telefon',
        'common.status': 'Holat',
        'common.active': 'Faol',
        'common.inactive': 'Nofaol',
        'common.date': 'Sana',
        'common.time': 'Vaqt',
        'common.price': 'Narx',
        'common.duration': 'Davomiyligi',
        'common.notes': 'Izohlar',
        'common.amount': 'Miqdor',
        'common.select': 'Tanlang...',
        'common.confirm': 'Ishonchingiz komilmi?',
        'common.done': 'Tayyor',
        // Settings
        'settings.title': 'Sozlamalar',
        'settings.appearance': "Ko'rinish",
        'settings.theme': 'Mavzu',
        'settings.themeLight': "Yorug'",
        'settings.themeDark': "Qorong'u",
        'settings.themeSystem': 'Tizim',
        'settings.language': 'Til',
        // Login
        'login.title': 'Medical CRM',
        'login.subtitle': 'Hisobingizga kiring',
        'login.email': 'Elektron pochta',
        'login.password': 'Parol',
        'login.emailPlaceholder': 'Elektron pochtangizni kiriting',
        'login.passwordPlaceholder': 'Parolingizni kiriting',
        'login.submit': 'Kirish',
        'login.submitting': 'Kirilmoqda...',
        // Dashboard titles
        'dashboard.title': 'Boshqaruv paneli',
        'dashboard.reception': 'Registratura paneli',
        'dashboard.doctor': 'Shifokor paneli',
        'dashboard.boss': 'Rahbar paneli',
        'dashboard.patientsToday': 'Bugungi yangi bemorlar',
        'dashboard.visitsToday': 'Bugungi tashriflar',
        'dashboard.revenueToday': 'Bugungi daromad',
        // Patients
        'patients.title': 'Bemorlar',
        'patients.add': "Bemor qo'shish",
        'patients.search': 'Bemorlarni qidirish...',
        'patients.firstName': 'Ism',
        'patients.lastName': 'Familiya',
        'patients.gender': 'Jins',
        'patients.male': 'Erkak',
        'patients.female': 'Ayol',
        'patients.other': 'Boshqa',
        'patients.noPatients': 'Bemorlar topilmadi',
        // Appointments
        'appointments.title': 'Navbatlar',
        'appointments.today': 'Bugungi navbatlar',
        'appointments.book': 'Navbatga yozish',
        'appointments.patient': 'Bemor',
        'appointments.doctor': 'Shifokor',
        'appointments.dateTime': 'Sana va vaqt',
        'appointments.selectPatient': 'Bemorni tanlang...',
        'appointments.selectDoctor': 'Shifokorni tanlang...',
        'appointments.noAppointments': "Bugun navbat yo'q",
        // Visits
        'visits.title': 'Tashriflar',
        'visits.today': 'Bugungi tashriflar',
        'visits.todaySchedule': 'Bugungi jadval',
        'visits.start': 'Tashrifni boshlash',
        'visits.complete': 'Yakunlash',
        'visits.completeTitle': 'Tashrifni yakunlash',
        'visits.diagnosis': 'Tashxis',
        'visits.diagnosisPlaceholder': 'Tashxisni kiriting...',
        'visits.diagnosisRequired': 'Tashxis kiritish shart',
        'visits.notesPlaceholder': "Qo'shimcha izohlar...",
        'visits.serviceRequired': "Kamida bitta xizmat tanlash shart",
        'visits.noVisits': "Bugun tashrif yo'q",
        'visits.noAppointments': "Bugun navbat yo'q",
        'visits.total': 'Jami',
        'visits.toothFormula': 'Tish formulasi',
        'visits.affectedTeeth': 'Muammoli tishlar',
        'visits.selectAffectedTeeth': 'Muammoli tishlarni belgilang',
        // Services
        'services.title': 'Tibbiy xizmatlar',
        'services.add': "Xizmat qo'shish",
        'services.name': 'Nom',
        'services.description': 'Tavsif',
        'services.qty': 'Soni',
        // Payment
        'payment.type': "To'lov turi",
        'payment.cash': 'Naqd',
        'payment.card': 'Karta',
        'payment.discount': 'Chegirma',
        'payment.discountType': 'Chegirma turi',
        'payment.discountValue': 'Chegirma miqdori',
        'payment.noDiscount': 'Chegirmasiz',
        'payment.percentage': 'Foiz',
        'payment.fixed': 'Belgilangan summa',
        // Staff
        'staff.title': 'Xodimlar',
        'staff.add': "Xodim qo'shish",
        'staff.role': 'Lavozim',
        'staff.doctor': 'Shifokor',
        'staff.receptionist': 'Registrator',
        // Contracts
        'contracts.title': 'Shifokor shartnomalari',
        'contracts.add': "Shartnoma qo'shish",
        'contracts.selectDoctor': 'Shifokorni tanlang',
        'contracts.sharePercent': 'Ulush foizi (%)',
        'contracts.startDate': 'Boshlanish sanasi',
        'contracts.endDate': 'Tugash sanasi (ixtiyoriy)',
        'contracts.ongoing': 'Davom etmoqda',
        'contracts.noContracts': "Shartnomalar yo'q.",
        // Expenses
        'expenses.title': 'Xarajatlar',
        'expenses.add': "Xarajat qo'shish",
        'expenses.category': 'Toifa',
        'expenses.rent': 'Ijara',
        'expenses.utilities': 'Kommunal',
        'expenses.supplies': 'Materiallar',
        'expenses.marketing': 'Marketing',
        'expenses.salary': 'Maosh',
        'expenses.other': 'Boshqa',
        'expenses.note': 'Izoh (ixtiyoriy)',
        'expenses.noExpenses': "Xarajatlar hali kiritilmagan.",
        // Salaries
        'salaries.title': 'Xodimlar maoshi',
        'salaries.add': "Maosh qo'shish",
        'salaries.selectStaff': 'Xodimni tanlang',
        'salaries.monthlyAmount': 'Oylik maosh ($)',
        'salaries.effectiveFrom': 'Kuchga kirish sanasi',
        'salaries.noSalaries': "Maoshlar hali sozlanmagan.",
        // Activity
        'activity.title': 'Shifokorlar faoliyati',
        'activity.allDoctors': 'Barcha shifokorlar',
        'activity.noLogs': "Faoliyat tarixi yo'q.",
        'activity.entity': 'Obyekt',
        'activity.details': "Tafsilotlar",
        'activity.action': 'Harakat',
        'activity.visitStarted': '🏥 Tashrif boshlandi',
        'activity.visitFinished': '✅ Tashrif yakunlandi',
        'activity.statusChanged': "📅 Holat o'zgardi",
        // Reports
        'reports.financialReports': 'Moliyaviy hisobotlar',
        'reports.subtitle': 'Oylik moliyaviy sharh va foyda tahlili',
        'reports.totalRevenue': 'Jami daromad',
        'reports.doctorEarnings': 'Shifokor ulushi',
        'reports.expenses': 'Jami xarajatlar',
        'reports.salaries': 'Xodimlar maoshi',
        'reports.grossProfit': 'Yalpi foyda',
        'reports.netProfit': 'Sof foyda',
        'reports.revenueByDoctor': "Shifokorlar bo'yicha daromad",
        'reports.expensesByCategory': "Toifalar bo'yicha xarajatlar",
        'reports.profitBreakdown': 'Moliyaviy taqsimot',
        'reports.additionalStats': "Qo'shimcha statistika",
        'reports.visitsCount': 'Jami tashriflar',
        'reports.patientsCount': 'Bemorlar',
        'reports.totalDiscount': 'Jami chegirmalar',
        'reports.avgPerVisit': "Tashrif uchun o'rtacha",
        'reports.noData': "Tanlangan davr uchun ma'lumot yo'q",
        // Table headers
        'table.earning': 'Daromad',
        'table.revenue': 'Tushum',
        'table.service': 'Xizmat',
        // Status
        'status.scheduled': 'Rejalashtirilgan',
        'status.confirmed': 'Tasdiqlangan',
        'status.in_progress': 'Jarayonda',
        'status.completed': 'Yakunlangan',
        'status.cancelled': 'Bekor qilingan',
        'status.no_show': 'Kelmadi',
        'status.started': 'Boshlangan',
        // Treatment Plans
        'treatmentPlan.title': 'Davolash Rejalari',
        'treatmentPlan.create': 'Reja Yaratish',
        'treatmentPlan.planTitle': 'Reja nomi',
        'treatmentPlan.planTitlePlaceholder': 'masalan: Implant o\'rnatish',
        'treatmentPlan.steps': 'Bosqichlar',
        'treatmentPlan.addStep': 'Bosqich qo\'shish',
        'treatmentPlan.stepDescription': 'Bosqich tavsifi',
        'treatmentPlan.stepPlaceholder': 'masalan: Tozalash, Rentgen',
        'treatmentPlan.noPlans': 'Davolash rejalari yo\'q',
        'treatmentPlan.progress': 'Jarayon',
        'treatmentPlan.markComplete': 'Bajarildi deb belgilash',
        'treatmentPlan.pending': 'Kutilmoqda',
        'treatmentPlan.completed': 'Bajarildi',
        'treatmentPlan.inProgress': 'Jarayonda',
        'treatmentPlan.patientPlans': 'Bemor davolash rejalari',
        'treatmentPlan.save': 'Saqlash',
        'treatmentPlan.finish': 'Tugatish va To\'lash',
        'treatmentPlan.saved': 'Davolash rejasi saqlandi. Keyingi tashrifda davom eting.',
    },
    ru: {
        // Navigation
        'nav.dashboard': 'Панель управления',
        'nav.patients': 'Пациенты',
        'nav.appointments': 'Записи',
        'nav.visits': 'Визиты',
        'nav.services': 'Услуги',
        'nav.staff': 'Персонал',
        'nav.contracts': 'Контракты',
        'nav.expenses': 'Расходы',
        'nav.salaries': 'Зарплаты',
        'nav.reports': 'Отчёты',
        'nav.activity': 'Активность',
        'nav.settings': 'Настройки',
        'nav.logout': 'Выход',
        'nav.brand': 'Medical CRM',
        // Common
        'common.save': 'Сохранить',
        'common.cancel': 'Отмена',
        'common.delete': 'Удалить',
        'common.edit': 'Редактировать',
        'common.create': 'Создать',
        'common.add': 'Добавить',
        'common.search': 'Поиск',
        'common.loading': 'Загрузка...',
        'common.noData': 'Нет данных',
        'common.refresh': 'Обновить',
        'common.filter': 'Фильтр',
        'common.to': 'до',
        'common.actions': 'Действия',
        'common.name': 'Имя',
        'common.email': 'Эл. почта',
        'common.phone': 'Телефон',
        'common.status': 'Статус',
        'common.active': 'Активен',
        'common.inactive': 'Неактивен',
        'common.date': 'Дата',
        'common.time': 'Время',
        'common.price': 'Цена',
        'common.duration': 'Длительность',
        'common.notes': 'Заметки',
        'common.amount': 'Сумма',
        'common.select': 'Выберите...',
        'common.confirm': 'Вы уверены?',
        'common.done': 'Готово',
        // Settings
        'settings.title': 'Настройки',
        'settings.appearance': 'Оформление',
        'settings.theme': 'Тема',
        'settings.themeLight': 'Светлая',
        'settings.themeDark': 'Тёмная',
        'settings.themeSystem': 'Системная',
        'settings.language': 'Язык',
        // Login
        'login.title': 'Medical CRM',
        'login.subtitle': 'Войдите в свой аккаунт',
        'login.email': 'Эл. почта',
        'login.password': 'Пароль',
        'login.emailPlaceholder': 'Введите эл. почту',
        'login.passwordPlaceholder': 'Введите пароль',
        'login.submit': 'Войти',
        'login.submitting': 'Вход...',
        // Dashboard titles
        'dashboard.title': 'Панель управления',
        'dashboard.reception': 'Панель регистратуры',
        'dashboard.doctor': 'Панель врача',
        'dashboard.boss': 'Панель руководителя',
        'dashboard.patientsToday': 'Новых пациентов сегодня',
        'dashboard.visitsToday': 'Визитов сегодня',
        'dashboard.revenueToday': 'Выручка сегодня',
        // Patients
        'patients.title': 'Пациенты',
        'patients.add': 'Добавить пациента',
        'patients.search': 'Поиск пациентов...',
        'patients.firstName': 'Имя',
        'patients.lastName': 'Фамилия',
        'patients.gender': 'Пол',
        'patients.male': 'Мужской',
        'patients.female': 'Женский',
        'patients.other': 'Другой',
        'patients.noPatients': 'Пациенты не найдены',
        // Appointments
        'appointments.title': 'Записи',
        'appointments.today': 'Записи на сегодня',
        'appointments.book': 'Записать',
        'appointments.patient': 'Пациент',
        'appointments.doctor': 'Врач',
        'appointments.dateTime': 'Дата и время',
        'appointments.selectPatient': 'Выберите пациента...',
        'appointments.selectDoctor': 'Выберите врача...',
        'appointments.noAppointments': 'Нет записей на сегодня',
        // Visits
        'visits.title': 'Визиты',
        'visits.today': 'Визиты сегодня',
        'visits.todaySchedule': 'Расписание на сегодня',
        'visits.start': 'Начать визит',
        'visits.complete': 'Завершить',
        'visits.completeTitle': 'Завершить визит',
        'visits.diagnosis': 'Диагноз',
        'visits.diagnosisPlaceholder': 'Введите диагноз...',
        'visits.diagnosisRequired': 'Диагноз обязателен',
        'visits.notesPlaceholder': 'Дополнительные заметки...',
        'visits.serviceRequired': 'Требуется хотя бы одна услуга',
        'visits.noVisits': 'Нет визитов сегодня',
        'visits.noAppointments': 'Нет записей на сегодня',
        'visits.total': 'Итого',
        'visits.toothFormula': 'Зубная формула',
        'visits.affectedTeeth': 'Проблемные зубы',
        'visits.selectAffectedTeeth': 'Отметьте проблемные зубы',
        // Services
        'services.title': 'Медицинские услуги',
        'services.add': 'Добавить услугу',
        'services.name': 'Название',
        'services.description': 'Описание',
        'services.qty': 'Кол-во',
        // Payment
        'payment.type': 'Тип оплаты',
        'payment.cash': 'Наличные',
        'payment.card': 'Карта',
        'payment.discount': 'Скидка',
        'payment.discountType': 'Тип скидки',
        'payment.discountValue': 'Размер скидки',
        'payment.noDiscount': 'Без скидки',
        'payment.percentage': 'Процент',
        'payment.fixed': 'Фикс. сумма',
        // Staff
        'staff.title': 'Сотрудники',
        'staff.add': 'Добавить сотрудника',
        'staff.role': 'Роль',
        'staff.doctor': 'Врач',
        'staff.receptionist': 'Регистратор',
        // Contracts
        'contracts.title': 'Контракты врачей',
        'contracts.add': 'Добавить контракт',
        'contracts.selectDoctor': 'Выберите врача',
        'contracts.sharePercent': 'Доля (%)',
        'contracts.startDate': 'Дата начала',
        'contracts.endDate': 'Дата окончания (опц.)',
        'contracts.ongoing': 'Бессрочный',
        'contracts.noContracts': 'Контрактов пока нет.',
        // Expenses
        'expenses.title': 'Расходы',
        'expenses.add': 'Добавить расход',
        'expenses.category': 'Категория',
        'expenses.rent': 'Аренда',
        'expenses.utilities': 'Коммунальные',
        'expenses.supplies': 'Материалы',
        'expenses.marketing': 'Маркетинг',
        'expenses.salary': 'Зарплата',
        'expenses.other': 'Другое',
        'expenses.note': 'Примечание (опц.)',
        'expenses.noExpenses': 'Расходов пока нет.',
        // Salaries
        'salaries.title': 'Зарплаты сотрудников',
        'salaries.add': 'Добавить зарплату',
        'salaries.selectStaff': 'Выберите сотрудника',
        'salaries.monthlyAmount': 'Месячная сумма ($)',
        'salaries.effectiveFrom': 'Действует с',
        'salaries.noSalaries': 'Зарплаты пока не настроены.',
        // Activity
        'activity.title': 'Журнал активности врачей',
        'activity.allDoctors': 'Все врачи',
        'activity.noLogs': 'Журнал активности пуст.',
        'activity.entity': 'Объект',
        'activity.details': 'Детали',
        'activity.action': 'Действие',
        'activity.visitStarted': '🏥 Визит начат',
        'activity.visitFinished': '✅ Визит завершён',
        'activity.statusChanged': '📅 Статус изменён',
        // Reports
        'reports.financialReports': 'Финансовые отчёты',
        'reports.subtitle': 'Ежемесячный финансовый обзор и анализ прибыли',
        'reports.totalRevenue': 'Общий доход',
        'reports.doctorEarnings': 'Заработок врачей',
        'reports.expenses': 'Общие расходы',
        'reports.salaries': 'Зарплаты персонала',
        'reports.grossProfit': 'Валовая прибыль',
        'reports.netProfit': 'Чистая прибыль',
        'reports.revenueByDoctor': 'Доход по врачам',
        'reports.expensesByCategory': 'Расходы по категориям',
        'reports.profitBreakdown': 'Финансовая структура',
        'reports.additionalStats': 'Дополнительная статистика',
        'reports.visitsCount': 'Всего визитов',
        'reports.patientsCount': 'Пациенты',
        'reports.totalDiscount': 'Всего скидок',
        'reports.avgPerVisit': 'Средний чек',
        'reports.noData': 'Нет данных за выбранный период',
        // Table headers
        'table.earning': 'Заработок',
        'table.revenue': 'Выручка',
        'table.service': 'Услуга',
        // Status
        'status.scheduled': 'Запланировано',
        'status.confirmed': 'Подтверждено',
        'status.in_progress': 'В процессе',
        'status.completed': 'Завершено',
        'status.cancelled': 'Отменено',
        'status.no_show': 'Не пришёл',
        'status.started': 'Начато',
        // Treatment Plans
        'treatmentPlan.title': 'Планы лечения',
        'treatmentPlan.create': 'Создать план',
        'treatmentPlan.planTitle': 'Название плана',
        'treatmentPlan.planTitlePlaceholder': 'напр.: Установка импланта',
        'treatmentPlan.steps': 'Этапы',
        'treatmentPlan.addStep': 'Добавить этап',
        'treatmentPlan.stepDescription': 'Описание этапа',
        'treatmentPlan.stepPlaceholder': 'напр.: Чистка, Рентген',
        'treatmentPlan.noPlans': 'Нет планов лечения',
        'treatmentPlan.progress': 'Прогресс',
        'treatmentPlan.markComplete': 'Отметить выполненным',
        'treatmentPlan.pending': 'Ожидает',
        'treatmentPlan.completed': 'Выполнено',
        'treatmentPlan.inProgress': 'В процессе',
        'treatmentPlan.patientPlans': 'Планы лечения пациента',
        'treatmentPlan.save': 'Сохранить',
        'treatmentPlan.finish': 'Завершить и оплатить',
        'treatmentPlan.saved': 'План лечения сохранён. Продолжите на следующем визите.',
    },
};

export function SettingsProvider({ children }: { children: ReactNode }) {
    const [theme, setThemeState] = useState<Theme>('light');
    const [language, setLanguageState] = useState<Language>('en');
    const [mounted, setMounted] = useState(false);

    useEffect(() => {
        setMounted(true);
        // Load saved settings
        const savedTheme = localStorage.getItem('theme') as Theme;
        const savedLang = localStorage.getItem('language') as Language;
        if (savedTheme) setThemeState(savedTheme);
        if (savedLang) setLanguageState(savedLang);
    }, []);

    useEffect(() => {
        if (!mounted) return;

        // Apply theme
        const root = document.documentElement;
        root.classList.remove('light', 'dark');

        if (theme === 'system') {
            const systemTheme = window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light';
            root.classList.add(systemTheme);
        } else {
            root.classList.add(theme);
        }

        localStorage.setItem('theme', theme);
    }, [theme, mounted]);

    const setTheme = (newTheme: Theme) => {
        setThemeState(newTheme);
    };

    const setLanguage = (lang: Language) => {
        setLanguageState(lang);
        localStorage.setItem('language', lang);
    };

    const t = (key: string): string => {
        return translations[language][key] || key;
    };

    if (!mounted) {
        return null;
    }

    return (
        <SettingsContext.Provider value={{ theme, setTheme, language, setLanguage, t }}>
            {children}
        </SettingsContext.Provider>
    );
}

export function useSettings() {
    const context = useContext(SettingsContext);
    if (!context) {
        throw new Error('useSettings must be used within a SettingsProvider');
    }
    return context;
}
